name: PIG 镜像 action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        id: vars
        run: |
          IMAGE_NAME="mysql/mysql-server"
          IMAGE_TAG="8.0.32"
          TARGET_REGISTRY="registry.cn-hangzhou.aliyuncs.com"
          TARGET_REPOSITORY="dockerhub_mirror"

          # Extract namespace if present
          if [[ "$IMAGE_NAME" == *"/"* ]]; then
            NAMESPACE=$(echo $IMAGE_NAME | cut -d'/' -f1)
            IMAGE=$(echo $IMAGE_NAME | cut -d'/' -f2)
          else
            NAMESPACE=""
            IMAGE=$IMAGE_NAME
          fi

          # Set environment variables
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "TARGET_REGISTRY=$TARGET_REGISTRY" >> $GITHUB_ENV
          echo "TARGET_REPOSITORY=$TARGET_REPOSITORY" >> $GITHUB_ENV
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ env.TARGET_REGISTRY }}

      - name: Pull, tag, and push Docker image
        run: |
          docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          if [ -n "${{ env.NAMESPACE }}" ]; then
            TARGET_IMAGE="${{ env.TARGET_REGISTRY }}/${{ env.TARGET_REPOSITORY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
          else
            TARGET_IMAGE="${{ env.TARGET_REGISTRY }}/${{ env.TARGET_REPOSITORY }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
          fi
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} $TARGET_IMAGE
          docker push $TARGET_IMAGE
